### ISSUE TITLE
Linker errors while building

### ISSUE THREAD

**Issue by mnowotnik** [bryphe/revery-quick-start#24]
It seems builder uses external version of the pango library. 
Relevant error fragment:

```
    //usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ft_face_create_cached'
    //usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ft_face_create'
    collect2: error: ld returned 1 exit status
```

**Comment by mstallmo** [comment]
Had the same issue: Running this on Ubuntu 18.04

**Comment by bryphe** [comment]
May be related to this: https://github.com/revery-ui/revery/issues/339

**Comment by glennsl** [comment]
Closing this due to staleness. So much has changed since this was created that it seems unlikely it's still an issue. But if it is, don't hesitate to let me know!
