### ISSUE TITLE
esy build fails when missing libpng

### ISSUE THREAD

**Issue by kyldvs** [bryphe/revery-quick-start#34]
on macOS 10.14.5

I cloned this repo then ran

```
esy install
esy build
```

The build fails with this error: https://gist.github.com/kyldvs/953cf85827c40f5d7ea656146915fd8a

I was able to fix it by installing libpng

```
brew install libpng
```

(there was also a warning about missing `/opt/local/bin` which I fixed with `sudo mkdir -p /opt/local/bin`, things worked even with the warning though)

**Comment by kyldvs** [comment]
(Figured I would create an issue in case other have same problem. Feel free to close since there is a clear fix ... install the missing dependencies. Detecting the issue and providing a better error message could be helpful though!)

**Comment by ManasJayanth** [comment]
I have packaged [libpng for esy](https://github.com/esy-packages/esy-libpng). I'm not sure, however, if it this template repo, or revery that should depend on it.

cc @bryphe

**Comment by glennsl** [comment]
I updated the README to point to Revery's requirements in #54 , which should hopefully prevent this and similar issues in the future. Thanks for reporting!
