### ISSUE TITLE
Build error on easy-format and jbuilder

### ISSUE THREAD

**Issue by darryldspencer** [bryphe/revery-quick-start#37]
Error message when I tried to build was:
info building @opam/cmdliner@opam:1.0.2@8ab0598a
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/easy-format@opam:1.3.1
    # esy-build-package: pwd: C:\Users\DarrylSpencer\.esy\3_\b\opam__s__easy_format-opam__c__1.3.1-386c7282
    # esy-build-package: running: "jbuilder" "build" "-p" "easy-format" "-j" "4"
    The jbuilder binary is deprecated and will cease to be maintained in July 2019.
    Please switch to dune instead.
    File "test/jbuild", line 1, characters 0-0:
    Warning: jbuild files are deprecated, please convert this file to a dune file instead.
    Note: You can use "dune upgrade" to convert your project to dune.
    Error: I don't know about package easy-format (passed through --only-packages/--release)
    error: command failed: "jbuilder" "build" "-p" "easy-format" "-j" "4" (exited with 1)
    esy-build-package: exiting with errors above...

  building @opam/easy-format@opam:1.3.1
esy: exiting due to errors above

**Comment by glennsl** [comment]
Seems like this has been fixed long ago since we're not using jbuilder anymore. Therefore closing this, but let me know if there's still an issue!
