### ISSUE TITLE
esy build fails on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by kokjinsam** [bryphe/revery-quick-start#40]
I followed the instructions on README and got the following error:

```bash
info building esy-cmake@0.3.5@d41d8cd9
info building reason-font-manager@2.0.0@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: reason-font-manager@2.0.0
    # esy-build-package: pwd: /home/sammkj/.esy/3___________________________________________________________________/b/reason_font_manager-2.0.0-57a2ccff
    # esy-build-package: running: 'refmterr' 'dune' 'build' '-p' 'reason-font-manager'
             gcc src/FontManagerLinux.o (exit 1)
    (cd _build/default/src && /usr/bin/gcc -I /home/sammkj/.esy/3___________________________________________________________________/i/ocaml-4.7.1004-a6ae015e/lib/ocaml -O2 -fno-strict-aliasing -fwrapv -fPIC -fPIC -lstdc++ -o FontManagerLinux.o -c FontManagerLinux.cpp)
    FontManagerLinux.cpp:3:10: fatal error: fontconfig/fontconfig.h: No such file or directory
     #include <fontconfig/fontconfig.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command failed: 'refmterr' 'dune' 'build' '-p' 'reason-font-manager' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building reason-font-manager@2.0.0
esy: exiting due to errors above
```

**Comment by kyldvs** [comment]
I had the same issue, I had to install these packages before finally getting stuck again anyway :)

You can try them one at a time and build after each to see which you need.

```
sudo apt-get install m4
sudo apt-get install libfontconfig1-dev
sudo apt-get install ragel
sudo apt-get install libbz2-dev
sudo apt-get install libx11-dev
sudo apt-get install libgtk-3-dev
```

Now I'm stuck with this error: https://gist.github.com/kyldvs/8355fe03ab2844584c1b3d6875fc43ab

**Comment by zploskey** [comment]
I ran up against the same issue, @kyldvs. I think that harfbuzz must have initially been compiled without glib support (cached from before I installed the development package `libglib2.0-dev`). I was tipped off by [this post](https://lists.osgeo.org/pipermail/mapserver-dev/2014-October/014250.html). I had to remove the cached builds for harfbuzz.

```
rm -r ~/.esy/3/b/esy_harfbuzz*
rm -r ~/.esy/3/i/esy_harfbuzz*
```
Then Revery built successfully for me.

It would be cool is `esy` had a command to do a clean build or remove build artifacts. If it does I have missed it.

**Comment by TheDahv** [comment]
Here's everything I had to install to get up and running:

```
sudo apt install
  libbz2-dev ragel \
  libfontconfig1-dev \
  libgl1-mesa-dev \
  libglu1-mesa-dev \
  libgtk-3-dev \
  libxcursor-dev \
  libxi-dev \
  libxinerama-dev \
  libxrandr-dev \
  m4
```

If we get a consistent complete list, perhaps this is something to add to the README for linux/Ubuntu users in a PR

**Comment by jgaehring** [comment]
I ran into the same error, and installing all the packages that @kyldvs recommended solved it for me.

**Comment by glennsl** [comment]
I updated the README to just refer to Revery's requirements in https://github.com/revery-ui/revery-quick-start/pull/54, which should hopefully prevent this confusion in the future.

Thanks for reporting though, for everyone helping out, and sorry for the late reply. This repository has unfortunately been severely neglected it seems.
