### ISSUE TITLE
`esy install` fails on ubuntu 19.10

### ISSUE THREAD

**Issue by JasoonS** [bryphe/revery-quick-start#57]
Hi, I've followed all the instructions and made very sure all the dependencies for revery are installed. However when I run `esy install` I get the following error:

```
info install 0.6.2 (using package.json)
.... fetching timber@1.0.0esy: internal error, uncaught exception:
     Unix.Unix_error(Unix.ENOTEMPTY, "rename", "/home/jasoons/Documents/learning/revery/revery-quick-start/_esy/default/tmp/esy-402ae3")
     Raised at file "src/core/lwt.ml", line 2999, characters 20-29
     Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
     Called from file "esy-lib/Cli.re", line 263, characters 9-28
     Called from file "cmdliner_term.ml", line 25, characters 19-24
     Called from file "cmdliner.ml", line 25, characters 27-34
     Called from file "cmdliner.ml", line 116, characters 32-39
```

I'm using esy 0.6.2 .

I haven't tried much, but I've tried deleting the `~/.esy` folder and recloning this repo. But I still get the same error.

Thanks :)

**Comment by glennsl** [comment]
The error is reported inside the local `_esy` folder, so you should try just deleting that. If that still doesn't work, it would be helpful to see if you're able to build Revery directly.

**Comment by glennsl** [comment]
Also, if removing `_esy` doesn't work, try removing `esy.lock` as well.

**Comment by JasoonS** [comment]
Thanks a ton! Its working now.
