### ISSUE TITLE
"esy build" not working on windows

### ISSUE THREAD

**Issue by 625dennis** [bryphe/revery-quick-start#58]
```
hostname = DESKTOP-5EN5KN6
uname -m = x86_64
uname -r = 3.0.7(0.338/5/3)
uname -s = CYGWIN_NT-10.0
uname -v = 2019-04-30 18:08

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/bin
PATH: /usr/local/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /cygdrive/c/Windows/System32


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2745: checking build system type
configure:2759: result: x86_64-unknown-cygwin
configure:2779: checking host system type
configure:2792: result: x86_64-unknown-cygwin
configure:2812: checking target system type
configure:2825: result: x86_64-unknown-cygwin
configure:2922: checking for gsed
configure:2953: result: sed
configure:2981: checking for a BSD-compatible install
configure:3049: result: /usr/bin/install -c
configure:3060: checking whether build environment is sane
configure:3115: result: yes
configure:3263: checking for a thread-safe mkdir -p
configure:3302: result: /usr/bin/mkdir -p
configure:3309: checking for gawk
configure:3325: found /usr/bin/gawk
configure:3336: result: gawk
configure:3347: checking whether make sets $(MAKE)
configure:3369: result: yes
configure:3398: checking whether make supports nested variables
configure:3415: result: yes
configure:3558: checking for gcc
configure:3588: result: no
configure:3651: checking for cc
configure:3698: result: no
configure:3754: checking for cl.exe
configure:3784: result: no
configure:3808: error: in `/cygdrive/c/Users/Dennis/.esy/3/b/esy_ocaml__s__libffi-3.2.10-2543eff9/x86_64-unknown-cygwin':
configure:3810: error: no acceptable C compiler found in $PATH
See `config.log' for more details
```

Looks like cygwin isn't installing gcc

**Comment by 625dennis** [comment]
It looks like when I ran "npm i -g esy", it didn't include gcc in node_modules/esy-bash/.cygwin.

How do you guys get it to install?

**Comment by 625dennis** [comment]
I also get this when I run "esy install" after deleting /Users/User/.esy

```
esy install                                                  
info install 0.6.2 (using package.json)                                                                                    
info fetching: done                                                                                                        
info core-js@2.6.11: running postinstall lifecycle                                                                         
error: No such file or directory                                                                                            
  unpacking esy-skia@github:revery-ui/esy-skia#91b10c9                                                                       
  installing esy-skia@github:revery-ui/esy-skia#91b10c9                                                                  
esy: exiting due to errors above      
```

**Comment by glennsl** [comment]
I don't know much about the Windows build process, but maybe @CrossR or @bryphe might have some tips to offer. I am in the process of updating Revery in #59 to a version that doesn't require libffi, which might incidentally solve the initial problem at least. Although you'll still need a C compiler for other dependencies, so it probably won't get you far.

**Comment by bryphe** [comment]
Hmm, what command prompt are you running from, @625dennis ? 

It looks like you might be running in Cygwin - `esy` on Windows actually doesn't properly support or detect that - on Windows, you'll need to build from `cmd` or `powershell` (as administrator). We might need to update the docs to better reflect that-

**Comment by 625dennis** [comment]
@bryphe I tried running from cmd with administrator access.

**Comment by 625dennis** [comment]
I went into `node_modules/esy/node_modules/esy-bash/.cygwin/setup-x86-64.exe`. I have `mingw64-x86_64-gcc-core` which cygwin says is "GCC for Win64 toolchain (C, OpenMP)", but the log says I don't have `gcc`.

**Comment by 625dennis** [comment]
I added `gcc-g++` and my libffi built a lot further. Now I'm getting `/cygdrive/c/Users/Dennis/.esy/3/b/esy_ocaml__s__libffi-3.2.10-2543eff9/missing: line 81: makeinfo: command not found`.

**Comment by 625dennis** [comment]
Ok I added `gcc-g++` and `texinfo` using `node_modules/esy/node_modules/esy-bash/.cygwin/setup-x86-64.exe` and I got it to build. Now I'm missing some dll files. I'll let you know if I solve this.

**Comment by glennsl** [comment]
#59 now builds on the Windows CI VM. Earlier it had the same error with libffi as you posted initially, so it might be worth a shot to try that, or update to the latest Revery yourself. It's a one-line change:

https://github.com/revery-ui/revery-quick-start/blob/8e34c617548c981b3898d1c2e6a231b0fa22b67b/package.json#L35

**Comment by bryphe** [comment]
Most of the windows builds should actually be using the MingW cross-compiler (`x86_64-w64-mingw32-gcc`, `x86_64-w64-mingw32-g++`, etc) - this lets us build fully-native binaries, without any dependency on cygwin. So it seems like a bug that it should be using `gcc` to begin with - I wonder if `libffi` was the only case, or if it affects all of our native builds in this environment.

**Comment by 625dennis** [comment]
I think `libffi` is the only one that needed `gcc`.

I am now having trouble building the `skia.dll`. From my understanding, I have to build this dependency myself. Right now I am only able to generate `skia.lib` using [https://skia.org/user/build#windows](https://skia.org/user/build#windows). Any help would be great.

Does this maybe have to do with this?
```
esy install                                                  
info install 0.6.2 (using package.json)                                                                                    
info fetching: done                                                                                                        
info core-js@2.6.11: running postinstall lifecycle                                                                         
error: No such file or directory                                                                                            
  unpacking esy-skia@github:revery-ui/esy-skia#91b10c9                                                                       
  installing esy-skia@github:revery-ui/esy-skia#91b10c9                                                                  
esy: exiting due to errors above      
```

**Comment by bryphe** [comment]
Hmm, `esy-skia` should take care of building everything for you. You can try cloning `esy-skia` and running `esy install` and `esy build`. It does require the MSVC compiler though - if you don't have it, you'll need to run `npm install -g windows-build-tools` to pick it up.

**Comment by 625dennis** [comment]
Not sure why I'm now getting this error. I removed `gcc-g++` and `texinfo` from my cygwin. I don't think that should affect this.
```
info building @opam/lambda-term@opam:2.0.3@9465cf1c
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/lambda-term@opam:2.0.3
    # esy-build-package: pwd: C:\Users\Dennis\.esy\3\b\opam__s__lambda_term-opam__c__2.0.3-96bc18f8
    # esy-build-package: running: "dune" "build" "-p" "lambda-term" "-j" "4"
    Info: Creating file dune-project with this contents:
    | (lang dune 2.4)
    | (name lambda-term)
    File "src/dune", line 9, characters 2-50:
    9 |   (c_flags         (:standard (:include c_flags)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error: 'c_flags' was deleted in version 2.0 of the dune language. Use the
    (foreign_stubs ...) field instead.
    error: command failed: "dune" "build" "-p" "lambda-term" "-j" "4" (exited with 1)
    esy-build-package: exiting with errors above...

  building @opam/lambda-term@opam:2.0.3
esy: exiting due to errors above
```

**Comment by 625dennis** [comment]
I got a very large error when I tried building esy-skia. `esy-skia/_build` wasn't created, but there is `skia.dll` under `esy-skia/_esy/default/store/b/esy_skia-6177d565/out/Shared/`. Is this the expected behavior?

**Comment by 625dennis** [comment]
I installed `windows 8.1 sdk` to get rid of an error when building `skia`.

When I tried running `App.exe`, it said `SDL2.dll`, `skia.dll`, and `libstdc++-6.dll` were missing. I downloaded `SDL2` from their website, I used the built `skia.dll` from the `out/Shared` folder from above, and I copied the `.dll` files from `cygwin`. This managed to get the app to open with a blue background and a small white box in the center.

![image](https://user-images.githubusercontent.com/5957944/77867828-21222200-71f6-11ea-8b7c-9dd899c8c5eb.png)

**Comment by 625dennis** [comment]
Ok. So I had to move `Roboto.ttf` into `_build\default`.

![image](https://user-images.githubusercontent.com/5957944/77867950-a574a500-71f6-11ea-893f-e082a795f303.png)

Hopefully this step-by-step fix helps you guys figure out a way to make this framework easier to work with on Windows. Let me know if you need any more info.

**Comment by 625dennis** [comment]
Seems like you can actually run it with `npm run run` without having to grab the `.dll` or `.ttf` files
