### ISSUE TITLE
npm timber package question

### ISSUE THREAD

**Issue by Samsinite** [bryphe/revery-quick-start#71]
Learning some ReasonML and playing with Revery. Just trying to understand how things work, and saw a reference to `Timer` in the application, so I immediately thought this was somehow pulled in from the timber npm package specified in the `package.json` file. After more investigation -- and some outside assistance -- it appears that revery has a dependency from https://github.com/glennsl/timber. Is the `timber` npm package accidentally being included into the source code? Or is this used somewhere else?

**Comment by glennsl** [comment]
I'm not sure I understand the question. What makes you think it's accidentally included?
